name: Java 17 CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build and run MCBOT.jar
      run: |
        cd mcbot
        java -jar MCBOT.jar 65.108.21.254:25587 340 botjoiner 120 -1
