name: Java 17 CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: java 17
      run: |
        sudo apt install default-jre

    - name: Build and run MCBOT.jar
      run: |
        git clone https://github.com/nejason57mars/mcbot.git
        cd mcbot
        java -jar MCBOT.jar 65.108.21.254:25587 340 botjoiner 120 -1
